CREATE TABLE IF NOT EXISTS scores (play TEXT NOT NULL, ts INTEGER NOT NULL, day INTEGER NOT NULL, total INTEGER NOT NULL, idx INTEGER NOT NULL, title TEXT NOT NULL, pts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS scores_day ON scores (day);
CREATE INDEX IF NOT EXISTS scores_title ON scores (title);
